apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RCZ/YQlv0c+XG8tOhM7ue66uDz7qgGff2Cq6VJznAYVvqGFO9ptbhOz9cVVMBITmn9s2xHA=,iv:HSNKfpdmVwClpRMjK55H7e5i286ipvDhkycGIBAitBw=,tag:KV/NNgeCgxXxS1OmuvzaCg==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdVBaRU51ZEp0MS9JRHlS
        T0JrN2treXpVWVhnUkxKK2tvc3hZVDRaZWs0Cis5eWZ4eDYxZUlPaytpemtmOUZ1
        a1hSRm9rdHJrNm01T2czOEJkZnpLM2cKLS0tIGozeFNKdHlNaXFPNTR1QW5aVGll
        VE9lampSSEJKUWNXTFFpQVRiM1Y2eWsK447McJEibqum/GBG0bfbqHlRdanWtMMA
        /2ubeNshlU2/WoVr5xjZj4X5D7nXnZR/Peb9jqxVbki79HOygiLqdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:05:01Z"
  mac: ENC[AES256_GCM,data:sYGl9cOGGucHGSa1YVJvdz77dDQ6r/O6s7JgBhYrkvSI0Q/cgUMYDff8cJLRlf/+yCq/WbU4yOoWgoJEBZLg3UxfvMzRaw/1fldiOXUVZnnc/t3B9Pu986/mJGHGStRfmj2b9L6sABGyBqen3HJnpu/crGPi3IjJ8YQ8C9EQcyE=,iv:tFC4b1iHC62SNU8ZLXn8VDnQJK9Hl1F28yPe/knUHsY=,tag:kmcMsYjo73PU6ZJya8OJIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
