apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mQvQvxZEF0ih9wqDSPUOg4P5AcawYUEq37jc9S7Aguj0q+YX3DH1xWnatVNQhVxbv7boA04=,iv:UGMXapkm5DJ7GQ9GKE/TD0PS8l/EdHD+tKLqZgBE33w=,tag:MpVRApS3i05TGMi8JqN3Vw==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vm5Cbm1sVDhTZXFCY2ky
        SktCbWY2SDhxVUtUK2VsOU82UnpNNnlHOXl3CkxkZmhCYmZGODhkNEZCVld6OWRB
        UVBpa3N3YTFvaVZINmMwb2IvNjQ4U2MKLS0tIGtORGtXWlA5UFd2L2I0N2pFWVZU
        a0hFK1RhMWpvWms4bmpDczY1VDBBUVEKrY9UslDwp7zv4uVI01qni+u5i4LPRmH4
        wAqM1md530Q1fqFjtzRaW+10UDIzbQNd19YT/6jMUdNKEnSdY86OXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T17:37:17Z"
  mac: ENC[AES256_GCM,data:By59Mrd6Md74c5d/xKPtjWmP2SAvMlbOwk9N3asDltciJHg6c8iLc/r+KAJ+NC5WZ09nkCauKXTb8rF9KsYinyrSQbMPA5zXMzBzoltiOXkwZsuyow/T7BF4BSsah7YWuiBraX/SOE4iaZGc3SxJYP78+LXj6NWIPE/xUxEWC54=,iv:lVyTa4ERk7HSK42VNHPFXvWIPAZSa3YNfiQJtNo+cHw=,tag:4CYV4egkm2aXQMjIncP1dQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
