apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:HMU907kF8yQyXG7E0Q8yr/pk8KeyHqMIVGccKmuNSjK/+IeGXirtVpvl2S/OMgb+jvZRIo8=,iv:apn0WX8LzC9psMMnzH3l9+VI+VXPYu/cQ3RaIKaDUr8=,tag:8YPBLys06ZuKB/ovNFcqDQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSlBpVFpqaGpvMUY2bURH
        eU1nVVczaXhpR2puM0dMWnppVHkxSEVWdWk0ClNkZmQ3NC95NUZDN1BMTmdsMVVG
        NUR1V0dEeUQ2L3hzM3hrLzFzWnp4SmMKLS0tIFFEV0doeUN1VTFMZzkwN1g0ZkxJ
        Z0lOZE1kQ01ub2hXbDZMeGRKVEg5RGMK03oaZsIXNcMpDW7v0e1JqF1b1wpB6JxS
        77SZUD+ShJ3RP9v4G37gnSBulK0iofmgfO8y+R/kix05Rpy4hpRFoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:51:27Z"
  mac: ENC[AES256_GCM,data:t3kMz8T+jK8Y0cSumSaOFEkcWAzyDdBwMYFZBmUlDd8p6a5goi/pvmkndj43afKhp6v64f2ryn+yE0sonucsfrwkcKGO37gZOq7RsJzXRgxiGGt0Rpl6MFnncXAadFJLclODPv/nu9/y/0soJgkn/XTMoYp2CX9D6ccBFE3Ssv8=,iv:7ZsgJgON99W6vTyBSmu67VuPUN+kUKmxwfJCARXnWR8=,tag:VQ+MAbfNL223eSsILWUjjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
