apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZsjZpGAHnSG5t9dM,iv:wWTb+hHO8WSL7gQ++NI393lMH/AZQM08UwVcZwU/m0U=,tag:QzOXvfZrvHp14XEubiJ5RQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY2ovZE9PUllHTVFVS2lO
        TUlyTVQxWVo1b044d09oZE5zcTJzK0FtL3pBCmFXUFN3c1dsZit4MmRBVkJiclJK
        VCtseURNZmxDNllKZytzRHZpTXNNSlkKLS0tIEpYcmkzR25mT2xXVnBsVFQ4TEVq
        R1dTSGowN2ZOcktFaHpqempxaEVWY3cK0XogT8+59vaxVaER0yaohNgjX5DrTlhd
        dwNlgkH7olb5OGVxJ986avdEZ43w+cS3FkZ2wOkr7jjcyaWb/89oKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:51:28Z"
  mac: ENC[AES256_GCM,data:G9KdBAi9Zp1ve1PD/WJsw0DY6ejiEVQzKnAQupYwM8Ny9vIKEYH1JCV36E/FWqS4TjLltv4KomqiwyPnqWNMmNUjrPZnHfUfDmGHpAfm7YLOD3Kb3EUK/H1MMgMDWAu18InsCykiGu/VHzT0Q/P17siUge4ojymDPYvxT+5cvrw=,iv:AuisGqoz7xpPD6+ywWIi1TUxaCovCiR67cvnIlPGX/M=,tag:LHXTsZdwtinvMeOYwddF7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
