apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:d4m8MBdhszmacGo9,iv:A6PjrXQgFpTS4scENpA11Sveqg4xDlavF7975KW13fE=,tag:0kwyzOGeoQ9rTO/bkquAhQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnAyekRPZXA1dzNxdStq
        KytFUlBhUU5MY1hiRmNNZVdyMjNYT0lmd0JjCmxBbEpqUXREUHV1ZWxaaTVaU1I5
        aEhVOTVOK25vd1ZCVTVqWDB2bUYvcUEKLS0tIFNwVXFUcldOYVowV2R4MDlYNHUx
        NGlhZ0VndUhYSFlQRVBFdnh0aHRVVkkKg0fewmftvhEaNooXCl63HJCQyzfO0TLx
        X9mwciOJZ6TKUgLZCeoiWrIW6GJOuP+tcQ9hgx8K/1+h9B+TKwBcWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:05:02Z"
  mac: ENC[AES256_GCM,data:vERluBD4F5MAmjbtcPz7Nc7tQ2f6dtwqqCQn85ybOX9c7GidDOn49/pf/xPhvGvXONZwu99/UN9OL6IQfUkYBvWDuY8N9QRxXRbmp4avTerXBHnalmkdYY7ftCci0Rod76hrloq1pTuDSqyEeqK4bhHtJ0sSwkHzrSICtTxaUPY=,iv:wKxGUMue/g0fjr5elcu2h1aJeoDaSBCIpMrVLoE1m6k=,tag:pM4BWTX9Nt9kZ/WvmiXKGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
