apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RWXZClaAb2e/jTYn,iv:RJ7KnYbgtS8DL4z6Rp4s3EdTDqSqXo1icoend2/csSE=,tag:DbPHPjPHTd8RVcZ/OKcdzQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZXRmdHVyRERNNFpUL1c4
        VlQ5eFUxRnBmYjloN2hDY2pIc2Nud09DR1VjCkxOR0VDbDZJTVRJRzhrblhNbkJu
        Uk0vYVBCWlN3eFVtdjlUTnZNQkd5U1EKLS0tIHg2NkpXanplbWZuTTBqNVNaeDVP
        K2Q2dUt3cHdkOTArNGljSndtdjBNTW8KSu399hSxSA+YSCGJsUHrtks01nGeg4NL
        SdSdwTLRyxtfwTip9XnNIr4bKjX6DqDe443MOjGTGEqPfuCoRDxs0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:03:07Z"
  mac: ENC[AES256_GCM,data:/wAkWex7K1uqdQvA1BbABMoZhvJVdhabiK8W5rjHjFLUH818KIuwjJehMuQK3PA7b5QOXgnvRpB4OLofjTUugVutGITj5GNHH79qXPxxJCUgEErH7RR3bXym7VbkbNpx3ycikQ9pc/ZqJYADt/257gQ5LGx03tuFDbxtBWXDDFg=,iv:OzmEAKnpXq8K4lAWZLRbGjd+sf+dAtnUt2rdrQ1Ij24=,tag:nTlqk1o0YcqxMxs6fZQPtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
