apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6Ybh8/B0+YV9SokJlacg2K7xWb8J+89d7/Y5dJ/eosI=,iv:Q87LXF6eKrk4cW9uzPgOHx018FIr0ixaNpbYIOCpU+E=,tag:36ldIV++EFxNfdWJduaTaw==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Mk9iTkp1VzZGb0hqOUNn
        MnlIZkowRjdSZVFPejd6NGNsOTU5ZlN1MWk0Ck5zZTJDT1BvVFdYVzN3S1N3SGdQ
        ckNMRS9OWU1lZnNMdHRMakhOK3VTbTQKLS0tIGQ1QlJXeFFaZlpmcGZXT2xhNk50
        OFd0VVZodDNHdjZRcHdwMDNZTGtIaE0KVRfdYjRXV3kNxuRpObBSUzAzyAK1+ZxH
        OZScy6VRjF8tikZnw4s1/YjHw+QgjyWipx1UM5pjg218z+ihzFiOKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:05:01Z"
  mac: ENC[AES256_GCM,data:IbQ0cx3qiJTtjAomenQB7HPzBe83v+OvfOHlbFuRLdTz7V1WOs6tQaC0ZRMLz3ebFq9GMR6AJYUeQ/e6jDxm+KQEHmVDPxHDji5z8jNvBIXeO/O4N0Qgdo756mJZwWJtLSFoLmcPL1oflP0n5wC/GTg3Li4WcB26Xthi676H1A4=,iv:Wnpi5C/ONv1dDijiVg9+k1IWvNoSlEje8KvDhNomJgY=,tag:V5yR2bFfPbqev5DK+du2LA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
