apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YXdNpqIWJMKDzRrj5DkHj8qlnidARqnB00U47b4wHfU=,iv:aA+X/BHD76/VK7Da2OVIhbgV5a34xseRFNXZl2Kbd6Y=,tag:7M0EGcNuAXr+DaTeii5jAA==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UlVSWjkydmJKdGtIaHJv
        THFyc2NOWCtwSGVLUE5zODhzM2d2M1AyNGxBClRiUXoyRG1JVE1LNndpZHRYVERK
        VU5iY3IxSDRsemdyYzVzOC9zZ3dvVjQKLS0tIDMvNGZpQi9jRGEzT245VDQrd0Ft
        V1d5Y0tyQXhJRW0wWWFEV3RsMFlObEUK/CWMndsgHDq2lmpxqzDX3gQYeGiEan57
        xLmdmL6mgyve35X691vjnge0mTY1o3ZPJxu7AWG0XDYdSXxq31Uu+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T17:37:17Z"
  mac: ENC[AES256_GCM,data:HGogzIQwo8J+BIpQtOPBou4GE5H5N6TisDpPNKmoXFKbsgkzfcVsoHdx3K3jeAPw4iRsZYXgUS90LDexdVvE94B3Re2Lr9xWDGJTSbp4ZKbBAXP+7eiB2dmUNuaTYZ+0BUVgiK3vuCpZPRaebbuw0Wu2D2ie0Zs9LLTvDqvlISA=,iv:TuSfe/uvcIFEbaTU1AKRMJG0UFM+rVuMUGARnb0/Lyw=,tag:xkc2db9n6EVFWSLrB2q1iQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
