apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YosMOWJNIaH0oiTUTp+bLDXpAzxWqVP6UXvYPVnOgYk=,iv:Oq7f62ywLRdNH5IEOhvE5HkjiN+1m+AhMO94oyYIDY8=,tag:56CdDMjJDzW0FruO46RcMw==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVDZ0V3VLdnpZZ09QZEVK
        Sit6MlF0TFE1WHNrd3VQeURQa2ZIQStjenc4CmRYZ3UrSFpEL2w5UXJhVnhvVmJ1
        OEpjYWs2aEtkSXNaZmtOZ1ZYTExYWGsKLS0tIDBPalhrOHhsUTFHTk9sSDNEU2JZ
        dEVza1p2dVJRdjdpUE1ZU3J4dUM3V0UKO6Uvwyifa1mT6Vjh6xlEDpq8FpcC0Qcd
        eLlwtRSbTqMQcWZKU34tGxk87+0f2caQ4V0XZtuJRKRN5p6HM5eMOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:51:27Z"
  mac: ENC[AES256_GCM,data:Plv4xExnIO1XcGMuHTgQepdEK4/5x4ElJ9amUIdcPNLGYhnC3oPsFQd35s4JTLIDwFXVyrvBMOX6Vzq0coqyNcZ3x4PrcTHa/xZ11ZDwGm1uj8bpmzCKZzrm/Q3fdJL4tgF2wa1+lRXEtDUNY+bbOEwI9z53e66sflOGEHAPQm4=,iv:MS1R6iOOlQWiabp1pmNXk6jCKpbS+/TiOzBgnaXPepA=,tag:2qJ/WlkpTQNm+3As7bAMoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
