apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hDk88jcXy7BnHshgNiAJTwG6KyjumUnhvzDDgEfKevhYOR1lY4UiQIuJK6pfz82HfoZdgrUTbYFIF1O5QElUgaMtgHPqIp8HWQxaRDNqBSJTw3qlf1FVt6pW1h4hbd87zSMfqcfi7PHtoqimWSybd+nhjjJ5Q7Zvs1zcjjs0ywfmfxNZURvHaWY1uLz2q1slTT1EVxFNW+ouovg0ROpojRqWl3r/lDrzPAxhyE6MA8rd6QO/,iv:3n8MecOk7zEWxZgPpKMbNmplkwyCzMtu0katCrbvOHw=,tag:FTOTYP3ZWRy685OdTrjpLQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RGU3VktucVhSYWxmOFA4
        YWZMaElLWk5VQWI4elN1akZZMkVOdzBrdWhrCjRDN3pTWVllUmZsb1lQbzh6Ymhr
        aFlJaE1RVkl5V05pL1laSVNJcTB0SjgKLS0tIC9WV1RHSnVoOHF2TEJjNkF6cE5r
        M3ZBejdFdTNkSzFRQ3h3dVFiWUZrME0KLIBLIsR8qGoNVOmudGj0gsmW8rfpPQuu
        x+1uVo9nQLWkSXID7/m8ar+D6hHQbXNSrSC3/zHkz0ts8Q0x60kTqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:51:27Z"
  mac: ENC[AES256_GCM,data:sPeCICfywq5sknKkvBXmt5gsBSCFu8+kzG0quNqfiSnXp40/PikogaerC1rMtMLQB0EKhR5LBm/jqHdPuqlphoMNa3PZNklJluJEGbfMpvO7UtXnjG6YIUIIjM2LWpU2KPcQMaBmx0C5HpuSTpP5D4g34hPyMzsL0ROiAPLurBw=,iv:Q2MArGhfJsbXC7C4YVnX4RsYgkKjO5bz6wpLoXqGXGg=,tag:zUAZBKTLEaopihUulzh3Rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
