apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0r47b2DSMu/vuiyBuuJN5tuI9PeGjFF4fmUCXb0mk5DoevMAgBJz3obkceEj49okssscItOA54Yioqhk8ZiyVUJokPb87WR0Iar7WR+bc1FnmETAfPUAIOODbmsLlEUP6nO7jxzA4OyzFJFgOMFx6D9k7TGMGUKKw2UiuA5hFFbN86ZosL6phCK8kfpo6qNJ+QcVCVzs80abu3WqjlLkyqafDFmes5ZpnhUSrJ9eaygtErMH,iv:KWFEfgDBvf1eixLFrrjfzy/H7nAfy1oJO6cGC8arO28=,tag:UBCHF+plf/C018vgbtGAmA==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtazIwTVlMTEVLZXJsK3E3
        a21jYi9BdUNEQlJDMEVpNFpZVit0eEJweFRnCjAvREpLWEd0b1VCUVQyWTlUYU9X
        dEM5WDRtenB0aWd1N3dGbXJUOXhobUEKLS0tIHdJTEViNzVwaXFPWGEra1RJS1c0
        b1dNejZqOHVPT25qcDBVOFNGZGVlUzQK6TfJv/dDQUekWxtc4iEErLxZ0psskaqS
        5+oxjct1UBMCFGf2/6dkXGQCBNMhYg+ue7HS2pJQSKetTfEQh9lNNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:05:02Z"
  mac: ENC[AES256_GCM,data:TXogG4IvBUzcIeMRnPjV5S9cXtrAUSi8p7TcZIcwUuStN1TyQalv+gIY6Rt4PvTUvv6mQtaD4Yc3x0px8Wg5rs0bfGKbeHL9S2XpVkkPO2NNiUiQVGSRlx/J16mFYXR9S8VjDxuBS1yptD2xBNY939ytvF06nxMHvHivyprVfLQ=,iv:2Mpna0klMOkyW+SccDlZXroc5y0InA0h06Zu1cX8gPc=,tag:AH0Zg2+Vorh6J1Lt3uz8sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
