apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WHA/ip2Y3YYcafbUbl7xmIaS56uAU0PsC/JHy/F3Nh8J54EKYk8BZTI4UlQbPEwtk6HRrbAcEn2L6Tnj6/dmJKuQ934NypOr9wTzzl+UgIaM6OcVq1y9lf6GxzW4884R84VjVBwKoOdQ72+rFqekf/ANHiQ51IPY/TAbPhYnYvbTV2dVSPsJqViQsLU1ceF+09vdtfJZtAlB1nmsuNTw8fvCPK8EiWbm66OPaI4y1bedtCGy,iv:J1TeJ1ce4rpRDZP+En1qbgsf4SFn2Qr0IjokzfZ7DJI=,tag:ButuSKc36qinhjA/VLYilA==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOVlnZHZYMFJ4Q29Gclhr
        Q295VnY5OFBXL1IxTkFRb1huN2p6OGhiVFRnCklLaElKT1hMRmFMOUh6N1NQZnVr
        OEVqa0RJb3J6UHpram9ibGxKKzZTcDQKLS0tIG9QU2RnOTNOL0o1UmlDTXB0aHU0
        SDJMZ00wZ2owRDdKZTVqYjUyWGp0b2cKVGGb7mfwR2aBVrYtiHzjRwA3WzttN2WS
        FsQQ4wrXqXy6B5aX2x9Wr+rTytjYAsPPTO4XjeSfVo7q9ZCjrr42dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T17:37:17Z"
  mac: ENC[AES256_GCM,data:A2iAY7ayH6pl47jHMkJvpq3nrU+mBcpwVbKxjk5DaJ4z45muZ/gWsx4/d9mU3ESod1gIh/ayhaUg9CqrsYOe8DcUsNrxcFOp1Nauy2Ig7ayz25P4ZgpVmUkiujhffErAOwvPam2LwWGTK6/UQPOo9cL969wjxv0hnGsuZMOkNkw=,iv:ELzHfdVdTtqaKWyI3GLkF2X5feFSFcsBt5VDp9gq66Y=,tag:4lZo+F4BojE+Zm4sdRFCug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
