apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2lzTR4NH2IVDWCGzUXiMQs2oOpenqsPIOLLsASDBeoqUm9DYwI1tkJKnhQCXVPzU9QEK8TE=,iv:/zdjiyEXznjMI1SIBm7ykLPapir4606Kxr5Fm68v/og=,tag:q77hcu1oCy+9vG28EyjQqg==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRzVFb1pKQkt1WUt5ZEht
        aUQ3Q1lFUy9EVmxzamNmZUVnb2lYdGwwWERFCmZYNjRGMmNidVlQcEk1a2gxL3pi
        am1mcXVHYkgrSDJ3MFU2aWZLWHRZN1EKLS0tIHVFOVVnQ0o2OWt2Nk5HbGJXemhr
        SzhaTi8zbGttOStkOUd6MkN4TXdwME0K+WyJYCVLQ2M43sg6YoW3vVv9Q1TEyFe6
        UuXitG+WUeRoiaH/n6n1Ypkx3fmPD4YkYuP8ZemwQ927rutkhDtgYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:51:27Z"
  mac: ENC[AES256_GCM,data:4nabq4PMK+GMxFdTL7ifx2VtzUsloib3mlueKz/C531P18ULVAYNX2pV6TL0v0DXhK6pLZ2Zi0ii/Ynxivg258oskXCpBDfeGMotIpaLchSl+ArapanPHbrZO3Nb82fZoINhPU0uAOBFhqyxZjZLEubJZbVhy+Irr+LaHudtJJw=,iv:1inZaydjRoImY4vwAjiny+toh7T7HlaANqEIXxc1teE=,tag:9iH8zJHMRsWR7SuGlUd4+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
