apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:U7sJb+g6cpvUlHQjeztHVmadqR1BXlXuAELpSxojxmOXYmo0ZASRDj8Uc5CfXBA9LCNw9MI=,iv:IUqlVInHTcLn5f6Aal6wVb+bl5wRtP4BWbLcOFvN4p0=,tag:VZwm405msdDR1ppAuPCQKQ==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaWF4cGJTUFVHWWMyOTFO
        a2M1Z2ZzTTR5YUROSHVwL3FqVnRsTVBIN21zCjZoTlptNXg3WlU1NEdKcTZBUGNL
        RFRtZEp2MlE1Tkl6L1BWa0p4Yi9EN2cKLS0tIHNlQXVZUTg0dXptTVV5eUE2QjRZ
        ZE94bDdsbmxONVBmM1VVTEFTdDZ2dlkK9Ht4iG2SJigAclskctBBXUn4pQYr1l6O
        iDcFzAQiZc4oQ5o0GMoIiPJL0rHQJ+q3GvBNAqmq/X4qomlNWtGhqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T17:37:16Z"
  mac: ENC[AES256_GCM,data:VB3qoMgIknZhlnq9dstinm+Gsq4YO50dAK7+7uP6JS7RgWUs2REA9GcjMuuyWEoT2mBuaAKJSosuU5au03yHEoo7Dfto/8YUWhL9xYAFCUc5uj6FRWDzG7x9gDwBsHnHZ+6iWL9SylarS5TRN6rxiiJIGbEy9NwKfntSXyeulcs=,iv:N/fHdsupCNUzaG4V+xL+3fNvTN6J59txMsG81NOmy7s=,tag:KwQRh2ICm6k7CceOgNsqpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
