apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:R2mL/tZaT0Ksu1IybK2xglZ04RC74zjvqYbmK6mVAjWRPqIXRfOEaT6tn+aydoZKjFmZyho=,iv:dDVBXkqbQ/bS6g6Bv2k66r03a/IWa19sR10lijND9Dg=,tag:4rl51VA9xysS6ZOAxBUUbg==,type:str]
sops:
  age:
    - recipient: age1w7r75tga7dauc390pv7hw9cay0l2tun3evnqvytz0s96afddrvcqacqadc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcXlDVUNlYmlldlRvK1Jj
        c0JEZlRKS3owM3lXSEwydUM1KzZDRVNRbHlNCkMvdjRTa24rMXJMODNubEIzdUVp
        OTE5V0phTFROYXVaSmg1OGxQbSttblEKLS0tIE03RVA2eEdXSGJQdmx5aFVjaGtG
        UDRucDQ5V2FHYU81VzByNWZLWk5xeWMKB7CYXstvfCXqzonPIlygDWlrdPmPG7tc
        XZD9NrVAeh688qnVe5yO05wI7nF5XYRtfT8VBw0lidWoLd8+NIlntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:05:01Z"
  mac: ENC[AES256_GCM,data:pXY5q26/ZBGnG/MzdGyxVVVu4EiBC3bIHa0JGfg1dhNuVxkSDPGErt+3mDfidF14wXTIzvPrDJw1pMjXq+h291WT+n9rLXQtEWvGVP9Gr4xJ2EghjM373mekmYezffMriRLqOeqqK2nFnXU2tImIQDihiejRhuj0/bcsPfiDPgg=,iv:eJdxkJk0HeHQvrhRZU3Qk5C6pmVRJG319FbaJfToxkY=,tag:VDU9rGXnnM9FCtYD+t/PDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
