---
clusterName: AigisK8S

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.24.8.50:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.24.8.50"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "aigis-k8s-01"
    ipAddress: "10.24.8.10"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:75:c4:d1"
        dhcp: false
        addresses:
          - "10.24.8.10/24"
        routes:
          - gateway: "10.24.8.254"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.24.8.50"
  - hostname: "aigis-k8s-02"
    ipAddress: "10.24.8.11"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:8e:62:69"
        dhcp: false
        addresses:
          - "10.24.8.11/24"
        routes:
          - gateway: "10.24.8.254"
            network: 0.0.0.0/0
        mtu: 1500
# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

